homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('education/', views.education, name='education'),
    path('experience/', views.experience, name='experience'),
    path('food/', views.food, name='food'),
    path('travel/', views.travel, name='travel'),
    path('addfriend/', views.addfriend, name='addfriend'),
    path('seefriend/', views.seefriend, name='seefriend'),
    path('seefriend/deletefriend/<str:name>', views.deletefriend, name='deletefriend'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.forms import ModelForm

#Create your models here.
class ClassYear(models.Model):
    BATCH_CHOICES= [('Maung (2019)', 'Maung (2019)'),
    ('Quanta (2018)', 'Quanta (2018)'),
    ('Tarung (2017)', 'Tarung (2017)'),
    ('Omega (2016)', 'Omega (2016)'),
    ('Others', 'Others')]
    batch = models.CharField(max_length=255, choices=BATCH_CHOICES, default='NULL')

    def __str__(self):
        return self.batch

class Friends(models.Model):
    name = models.CharField(max_length=255, primary_key=True, default='')
    ClassYear = models.ForeignKey(ClassYear, on_delete=models.CASCADE, default='Fasilkom')
    hobby = models.CharField(max_length=255)
    food = models.CharField(max_length=255)
    drink = models.CharField(max_length=255)

    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from .models import Friends, ClassYear

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friends
        fields = ['name', 'ClassYear', 'hobby', 'food', 'drink']
        labels = {'name': 'Name',
                'ClassYear': 'Batch',
                'hobby': 'Hobby',
                'food': 'Favorite Food',
                'drink': 'Favorite Drink'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Friends, ClassYear
from . import forms


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def education(request):
    return render(request, 'education.html')

def experience(request):
    return render(request, 'experience.html')

def food(request):
    return render(request, 'food.html')

def travel(request):
    return render(request, 'travel.html')

def seefriend(request):
    friends = Friends.objects.all()
    classyear = ClassYear.objects.all()
    response = {'friends' : friends, 'classyear': classyear}
    return render(request, 'seefriend.html', response)

def addfriend(request):
    if request.method == 'POST':
        form = forms.FriendForm(request.POST)
        print(1)
        if form.is_valid():
            print(2)
            form.save()
            return redirect('homepage:seefriend')
    else:
        form = forms.FriendForm()
    return render(request, 'addfriend.html', {'form': form})

def deletefriend(request, name):
    friends = Friends.objects.get(name=name)
    friends.delete()
    return redirect('/seefriend/')

homepage/templates/about.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
    <title>About - Nabila Edina</title>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <hr>
            </div>
        </div>
    </div>    
    <div class="container">
        <div class="row align-items-center">
            <div class="col-sm">
                <hr style="width: 400px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
            <div class="col">
                <div class="title text-center">ABOUT</div>
            </div>
            <div class="col-sm">
                <hr style="width: 400px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
        </div>
    </div>
    
    
    <br>
    <br>
    
    <br>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <img src="{% static 'images/about.jpeg' %}" class="img-fluid">
            </div>
            <div class="col-sm">
                <h1>
                    Hi, I'm Edina!
                </h1>
                <p>
                    I’m a 19 years-old Computer Science student in University of Indonesia.
                    I’m a passionate and hard-working individual. I really like to travel and taste
                    its local food.  I love to eat and watch movies especially romantic-comedy 
                    movie. 
                </p>
                <div class="row">
                    <div class="col-sm">
                        <div class="row" id="skillsFollowMeRow">
                            <div class="col-sm">
                                <hr>
                            </div>
                            <div class="col-sm-3">
                                SKILLS
                            </div>
                            <div class="col-sm">
                                <hr>
                            </div>
                        </div>
                        <div class="row text-center mt-3" id="icon">
                            <div class="col-sm">
                                <img class="img-fluid" src="{% static 'images/python.png' %}">
                                    PYTHON
                            </div>
                            <div class="col-sm">
                                <img class="img-fluid" src="{% static 'images/java.png' %}">
                                 JAVA
                            </div>
                        </div>
                        <div class="row text-center mt-3" id="icon">
                            <div class="col-sm">
                                <img class="img-fluid" src="{% static 'images/html-5.png' %}">
                                HTML
                            </div>
                            <div class="col-sm">
                                <img class="img-fluid" src="{% static 'images/photoshop.png' %}">
                                PHOTOSHOP
                            </div>
                        </div>
                    </div>
                    <div class="col-sm">
                        <div class="row" id="skillsFollowMeRow">
                            <div class="col-sm">
                                <hr>
                            </div>
                            <div class="col-sm-6">
                                FOLLOW ME
                            </div>
                            <div class="col-sm">
                                <hr>
                            </div>
                        </div>
                        <div class="row text-center mt-3" id="icon">
                            <div class="col-sm">
                                <a href="https://www.instagram.com/nabilaedinaa/"><img class="img-fluid" src="{% static 'images/instagram copy.png' %}"></a>
                                INSTAGRAM
                            </div>
                            <div class="col-sm">
                                <a href="https://twitter.com/dinnn_tai_fung"><img class="img-fluid" src="{% static 'images/twitter copy.png' %}"></a>
                                TWITTER
                            </div>
                        </div>
                        <div class="row text-center mt-3" id="icon">
                            <div class="col-sm">
                                <a href="https://www.linkedin.com/in/nabilaedinaa/"><img class="img-fluid" src="{% static 'images/linkedin copy.png' %}"></a>
                                LINKEDIN
                            </div>
                            <div class="col-sm">
                                <a href="https://id.pinterest.com/nabilaedinaaa/"><img class="img-fluid" src="{% static 'images/pinterest copy.png' %}"></a>
                                PINTEREST
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
   
  
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% include 'copyright.html' %}
{% endblock %}

homepage/templates/addfriend.html
{% extends 'navbar.html' %}

{% load static %}

{% block content %}
<hr>
<title style="text-align: center;">Add Friends</title>
<br><br>
<h1 style="text-align: center;">Add Friends</h1>


<form method="post" action="{% url 'homepage:addfriend' %}">
    {% csrf_token %}
    <div style="margin-left: 10px; margin-right: 10px;">
    <div class="form-row">
        <div class="col-sm-1"></div>
        <div class="form-group col-sm-10">
            {% for fields in form %}
                {{ fields.label_tag }}
                <br>
                {{ fields }}
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <input style="align-content: center; margin-left: auto; margin-right: auto;" id="submitBtn" type="submit" class="btn btn-primary" value="Add">
        
    </div>
    </div>
    
</form>
<div class="container">
    <div class="row">
        <div class="col-sm">
        </div>
        <div class="col-sm" style="text-align: center;">
            <a href="/seefriend/"><button style="align-content: center; margin-left: auto; margin-right: auto;" type ="button" class="btn btn-primary">See Friends</button></a>
        </div>
        <div class="col-sm">
        </div>
    </div>
</div>


{% include 'copyright.html' %}
{% endblock %}

homepage/templates/copyright.html
<footer>
    <div style="text-align: center;">
        <br>
        <br>
        <br>
        © 2020 Nabila Edina. All right reserved.
    </div>
</footer>

homepage/templates/education.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<title>Education - Nabila Edina</title>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <hr>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-sm">
                <hr style="width: 300px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
            <div class="col-sm-5">
                <div class="title text-center">EDUCATION</div>
            </div>
            <div class="col-sm">
                <hr style="width: 300px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
        </div>
    </div>
    <div class="container" id="eduFont">
        <div class="row align-items-center">
            <div class="col-sm">
                <img class="eduImg" src="{% static 'images/makara-ui-fasilkom.png' %}">
            </div>
            <div class="col-sm-7">
                Faculty of Computer Science, University of Indonesia
                <br>
                2018 - Present
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <img class="eduImg" src="{% static 'images/sman.jpg' %}">
            </div>
            <div class="col-sm-7">
                <br>
                SMAN 8 Jakarta
                <br>
                2015 - 2018
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <img class="eduImg" src="{% static 'images/Logo_Labschool.png' %}">
            </div>
            <div class="col-sm-7">
                <br>
                SMP Labschool Cibubur
                <br>
                2012 - 2015
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <img class="eduImg" src="{% static 'images/sd-al-azhar-syifa-budi-cibinong.jpg' %}">
            </div>
            <div class="col-sm-7">
                <br>
                SD Al-Azhar Syifa Budi Cibubur
                <br>
                2006 - 2012
            </div>
        </div>
    </div>
    {% include 'copyright.html' %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock %}

homepage/templates/experience.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<title>Experience - Nabila Edina</title>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <hr>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-sm">
                <hr style="width: 300px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
            <div class="col-sm">
                <div class="title text-center">EXPERIENCE</div>
            </div>
            <div class="col-sm">
                <hr style="width: 300px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <div class="row">
            <div class="col-sm">
                <img class="img-fluid" src="{% static 'images/expe.png' %}">
            </div>
            <div class="col-sm">
                <img class="img-fluid" src="{% static 'images/expe1.png' %}">
            </div>
        </div>
    </div>
    {% include 'copyright.html' %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock %}

homepage/templates/food.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<title>Food - Nabila Edina</title>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <hr>
            </div>
        </div>
    </div>    
    <div class="container">
        <div class="row align-items-center">
            <div class="col-sm">
                <hr style="width: 400px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
            <div class="col">
                <div class="title text-center">FOOD</div>
            </div>
            <div class="col-sm">
                <hr style="width: 400px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="container">
        <div class="row text-center">
            <div class="col-sm title" style="font-size: 100px;">
                <br>
                <br>
                COMING SOON!
                <br>
                <br>
                <br>
                <br>
                <br>
            </div>
        </div>
    </div>
    {% include 'copyright.html' %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock %}

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Montserrat&display=swap" rel="stylesheet">
    <title>Home - Nabila Edina</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/0bb1ded335.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-2">

            </div>
            <div class="col-sm-8 text-center">
                <a href="{% url 'homepage:home' %}"><h1 class="head">NABILA EDINA</h1></a>
            </div>
            <div class="col-sm-2.5" style="padding-top: 25px;">
                <a href="https://www.instagram.com/nabilaedinaa/""><img src="{% static 'images/instagram.png' %}" style="width: 30px;"></a>
                <a href="https://www.facebook.com/nabilaedinaa"><img src="{% static 'images/facebook.png' %}" style="width: 30px;"></a>
                <a href="https://www.linkedin.com/in/nabilaedinaa/"><img src="{% static 'images/linkedin.png' %}" style="width: 30px;"></a>
                <a href="https://twitter.com/dinnn_tai_fung"><img src="{% static 'images/twitter.png' %}" style="width: 30px;"></a>
                <a href="https://id.pinterest.com/nabilaedinaaa/"><img src="{% static 'images/pinterest.png' %}" style="width: 30px;"></a>
            </div>
        </div>
    </div>
    
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <hr>
            </div>
        </div>
    </div>    
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <hr>
            </div>
        </div>
    </div>    
    <div class="container">
        <div class="row">
            <div class="col-sm text-center">
                <div class="welcome">
                    Welcome!
                </div>
                <div class="first_time">
                    First time to this site?
                </div>
                <a href="{% url 'homepage:about' %}"><h3 style="width: 500px; height: 102px;" class="start_here">START HERE</h3></a>
            </div>
            <div class="col-sm">
                <img src="{% static 'images/home.jpeg' %}" style="width: 500px; height: 660px;">
            </div>
        </div>
    </div>
    {% include 'copyright.html' %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    
    

</body>
</html>

homepage/templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/0bb1ded335.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-2 mb-1">
        <div class="row" id="navBar">
            <div class="col-sm">
                <a href="{% url 'homepage:home' %}"><i class="fas fa-home" style="font-size: 32px; color: black;"></i></a>
            </div>
            <div class="col-sm text-center">
                <a href="{% url 'homepage:about' %}">ABOUT</a>
            </div>
            <div class="col-sm text-center">
                <a href="{% url 'homepage:education' %}">EDUCATION</a>
            </div>
            <div class="col-sm text-center">
                <a href="{% url 'homepage:experience' %}">EXPERIENCE</a>
            </div>
            <div class="col-sm text-center">
                <a href="{% url 'homepage:travel' %}">TRAVEL</a>
            </div>
            <div class="col-sm text-center">
                <a href= "#" data-toggle="modal" data-target="#exampleModal">FOOD</a>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="false">
                    <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Coming Soon!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                        Sorry. Will be available soon.
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <a type="button" class="btn btn-primary" href="{% url 'homepage:food' %}">OK</a>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
            <div class="col-sm text-center">
                <a href="{% url 'homepage:addfriend' %}">FRIENDS</a>
            </div>
        </div>
    </div>
{% block content %}

{% endblock %}

    
</body>
</html>

homepage/templates/seefriend.html
{% extends 'navbar.html' %}

{% load static %}

{% block content %}
<hr>
<title>See Friends</title>
<br><br>
<h1 id="profh1" style="text-align: center;">My Friends</h1>

<table id="friendtable" class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Batch</th>
        <th scope="col">Hobby</th>
        <th scope="col">Fav Food</th>
        <th scope="col">Fav Drink</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for friend in friends %}
        <tr class="table-info">
          <td class="table-secondary">{{ friend.name }}</td>
          <td class="table-info">{{ friend.ClassYear }}</td>
          <td class="table-secondary">{{ friend.hobby }}</td>
          <td class="table-info">{{ friend.food }}</td>
          <td class="table-secondary">{{ friend.drink }}</td>
          <td><a href="/seefriend/deletefriend/{{friend.name}}"><button type ="button" class="btn btn-danger btn-sm mt-3">Delete</button></a></td>
          
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'homepage:addfriend' %}" style="text-decoration: none;"> 
    <button id="friendButton" type="button" class="btn btn-light">
      Add Friends</button> </a>
      {% include 'copyright.html' %}
{% endblock %}

homepage/templates/travel.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<title>Travel - Nabila Edina</title>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <hr>
            </div>
        </div>
    </div>    
    <div class="container">
        <div class="row align-items-center">
            <div class="col-sm">
                <hr style="width: 400px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
            <div class="col">
                <div class="title text-center">TRAVEL
                </div>
            </div>
            <div class="col-sm">
                <hr style="width: 400px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <img src="{% static 'images/swiss.jpeg' %}" style="width: 300px;">
                <h1 class="date text-center">July 11, 2016</h1>
                <h1 class="city text-center">Swiss</h1>
                <br>
                <img src="{% static 'images/penang.jpeg' %}" style="width: 300px;">
                <h1 class="date text-center">August 8, 2019</h1>
                <h1 class="city text-center">Penang</h1>
            </div>
            <div class="col-sm">
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <img src="{% static 'images/london.jpeg' %}" style="width: 300px; height: 400px;">
                <h1 class="date text-center">July 3, 2016</h1>
                <h1 class="city text-center">London</h1>
            </div>
            <div class="col-sm">
                <img src="{% static 'images/rome.jpeg' %}" style="width: 300px;">
                <h1 class="date text-center">July 14, 2016</h1>
                <h1 class="city text-center">Rome</h1>
                <br>
                <img src="{% static 'images/venice.jpeg' %}" style="width: 300px;">
                <h1 class="date text-center">July 13, 2016</h1>
                <h1 class="city text-center">Venice</h1>
            </div>
        </div>
    </div>
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-sm">
                        <hr style="width: 350px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
                    </div>
                    <div class="col">
                        <div class="list text-center">MY BUCKET LISTS</div>
                    </div>
                    <div class="col-sm">
                        <hr style="width: 350px;height: 0px;left: 50px;top: 50px;border: 1px solid #000000;border-width: 1px;transform: rotate(180deg)">
                    </div>
                </div>
                <div class="row text-center justify-contents-center">
                    <div class="col-sm">
                        <img src="{% static 'images/loc.png' %}" class="loc">
                        <p>Greece</p>
                    </div>
                    <div class="col-sm">
                        <img src="{% static 'images/loc.png' %}" class="loc">
                        <p>New Zealand</p>
                    </div>
                    <div class="col-sm">
                        <img src="{% static 'images/loc.png' %}" class="loc">
                        <p>Edinburgh</p>
                    </div>
                    <div class="col-sm">
                        <img src="{% static 'images/loc.png' %}" class="loc">
                        <p>Spain</p>
                    </div>
                    <div class="col-sm">
                        <img src="{% static 'images/loc.png' %}" class="loc">
                        <p>United States</p>
                    </div>
                </div>
            </div>
            
        </div>
        
    </div>
    {% include 'copyright.html' %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock %}